- 
  exp_name: "DVRF_SD3"
  dataset_yaml: images/mapping_file.yaml
  model_type: "SD3"
  T_steps: 50 # number off discrete timesteps
  B: 1 # batch size
  src_guidance_scale: 6
  tgt_guidance_scale: 16.5 
  num_steps: 50 # number of optimization steps
  seed: 41
  eta: 1.0 # with the progessive eta described in the paper
  scheduler_strategy: "descending" # "random" or "descending"
  lr: "custom" # to use the lr described in the paper, or just a constant float value
  optimizer: "SGD" # or "Adam"